name: Generate Sample Data

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/generate_sample_data.yml"
      - "Makefile"
      - "scripts/generate_sample_data.py"
      - "data/sample/manifests/**"

env:
  SAMPLE_DATA_PYTHON_VERSION: 3.9

jobs:
  generate:
    name: Generate Sample Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Python ${{ env.SAMPLE_DATA_PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.SAMPLE_DATA_PYTHON_VERSION }}
      - name: Install sample data generator dependencies
        run: python -m pip install electionguard==1.4.0 dacite==1.6.0 hypothesis
      - name: Package Sample Data
        run: make release-package-sample-data PYTHON=python
      - name: Publish Sample Data
        uses: actions/upload-artifact@v4
        with:
          name: sample-data
          path: |
            sample-data.zip
            sample-data.tar.gz
          overwrite: true
