name: Validate Pull Request

on: pull_request

env:
  PYTHON_VERSION: 3.10.14

jobs:
  validate: 
    name: Validate Documentation
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Change Directory
        run: cd ${{ github.workspace }}
      - name: Install packages
        run: pipenv install
      - name: Install MkDocs
        run: pipenv run make install
      - name: Lint
        run: pipenv run make lint