name: Release Build

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.14.0

jobs:
  publish: 
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv
      - name: Change Directory
        run: cd ${{ github.workspace }}
      - name: Install packages
        run: pipenv install
      - name: Deploy
        run: make deploy
      - name: Zip Sample Data
        run: make release-zip-sample-data
      - name: Publish Sample Data
        uses: actions/upload-artifact@v4
        with:
          name: sample-data
          path: sample-data.zip
          overwrite: true
      - name: Sync Labels
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.LABEL_TOKEN }}
        run: make labels
